version: "3.8"

services:
  app:
    build: .
    container_name: evro_node_todo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: localuser
      DB_PASS: password
      DB_NAME: evro_db
      DB_DIALECT: postgres
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
